# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ivan Kraljevic - personal pages

author:
  name: Ivan Kraljević
  email: ivan.kraljevic14+mysite@gmail.com
  cvurl: https://drive.google.com/open?id=1oSW9irIZo273UPpTs99ogikFo8qWSm7X

description: >- # this means to ignore newlines until "baseurl:"
  Ivan Kraljevic - personal pages
baseurl: ""
url: "https://ivankraljevic.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

#github_username:  IvanKraljevic

# Build settings
markdown: kramdown

#theme: minima
theme: jekyll-theme-midnight

plugins:
  - jekyll-feed
  - github-pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
